import Image from 'next/image'
import Head from 'next/head'
import styles from '@/styles/Menu.module.css'
import { Inter } from 'next/font/google'
import MenuItem from './MenuItem'
import RadioButtons from '@/pages/Radiobuttons'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const menu_items=[
    {title:"Home"},
    {title:"Services",
     submenu : [
       {title:"Digital Marketing"},
       {title:"Logo Designing"},
       {title:"Email-Marketing"},
       {title:"Online Courses"},
       {title:"Line Coaching"},
       {title:"Digital Marketing"},
       {title:"Digital Marketing"},
   
     ]
  
    },
    {title:"Contact"},
    {title:"Technologies"},
    {title:"Hardware"},
    {title:"Software"},
    {title:"About Us"}
   
  ]
  return (
    <div className={styles.container}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel='icon' href='/favicon.ico' />
    </Head>
     <div className={styles.header}>
      <ul>
        {menu_items.map((item,index) => {

            return <MenuItem item={item} key={index} depth={1}/>

        })}
      </ul>
     </div>
     <div>
      <RadioButtons />
     </div>
    </div>
  )
}
